CREATE TABLE CLIENT
(
    MAIL       VARCHAR(200),
    LAST_NAME  VARCHAR(50),
    FIRST_NAME VARCHAR(50),
    PASSWORD   TEXT,
    CONSTRAINT PK_CLIENT PRIMARY KEY (MAIL)
);

CREATE TABLE COMPANY
(
    ID   INTEGER,
    NAME VARCHAR(50),
    CONSTRAINT PK_COMPANY PRIMARY KEY (ID)
);

CREATE TABLE CLIENT_RESERVATION
(
    ID             UUID,
    CLIENT_MAIL    VARCHAR(200),
    RESERVATION_ID UUID,
    COMPANY_ID     INTEGER,
    CONSTRAINT PK_CLIENT_RESERVATION PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENT FOREIGN KEY (CLIENT_MAIL) REFERENCES CLIENT,
    CONSTRAINT FK_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY
);

INSERT INTO COMPANY
VALUES (1, 'SNCF');
INSERT INTO COMPANY
VALUES (2, 'LA RENFE');
